### ISSUE TITLE
how to get remaining time from this view

### ISSUE THREAD

**Issue by Niks345** [jsaman19/easyCountDownTimer#1]
I am using ur library and its working well.Just want to ask how can i get remaining time.

**Comment by jsaman19** [comment]
you must use this function and calculate remaining time :
`countDownTextview.setOnTick(new CountDownInterface() {
            @Override
            public void onTick(long time) {
                Log.i("main activty", "onTick");
                long second = (time % 60000) / 1000;
                long min = time / 60000;
                long hour = time / 360000;
            }

            @Override
            public void onFinish() {
                Log.i("main activity", "onFinish");
            }
        });`

**Comment by Niks345** [comment]
ok thanks for replay will do the same...
