### ISSUE TITLE
How to show time in two digits

### ISSUE THREAD

**Issue by PembaTamang** [jsaman19/easyCountDownTimer#3]
I want the time to be shown as 00:01:59 where all the values are in two digits how can that be done??

**Comment by muhammadkamranlatifraza** [comment]
I'm downloading code and will edit it to do this... then i'll post it here

**Comment by jsaman19** [comment]
> I want the time to be shown as 00:01:59 where all the values are in two digits how can that be done??

added in version 2.2.0
