### ISSUE TITLE
Bug using minutes/seconds

### ISSUE THREAD

**Issue by gipic** [jsaman19/easyCountDownTimer#4]
Hi thank you for this repository.
This view does not work if I call setTime using only minutes or only minutes with seconds.
Ex:
countDownTextview.setTime(0, 0, 1,0);
countDownTextview.setTime(0, 0, 0,30);
Widget is stuck between 0 : 0 : 0 : 0 and 0 : 0 : 0 : 1 in loop.

**Comment by jsaman19** [comment]
Hi man
Thank you for your report
I fixed this issue, please download a new version of this library (2.2.1)
good luck.
