### ISSUE TITLE
improvement and flexibility

### ISSUE THREAD

**Issue by Jacouille** [jsaman19/easyCountDownTimer#5]
Hi,
your library is very nice. I would really like to use it in my app but there is a few things that prevents me from doing so.

- When i put app:showDays="false" in my xml file, the days still show up with "00". It only removes the label. I have to programmatically setShowDays(false) to remove the "00".
- I also went through your code to see the logic because i came to realize that you call startTimer() when we setTime and in the constructor. Would it be possible to not start the timer in these functions. I'd like to start the timer myself when the user press a button.
- Maybe it's just me but i can't center horizontally the textView inside the EasyCountDownTimer in my xml. It's placed inside a constrainLayout with other elements. It's always align to the left side.
![image](https://user-images.githubusercontent.com/49291068/77690395-9a611100-6f79-11ea-9bcf-d6515fa121ec.png)

Thank you very much :)

**Comment by jsaman19** [comment]
Thank you for your report.
I will try to fix these in the next days.

**Comment by jsaman19** [comment]
please check version 2.3.0

**Comment by muhammedgul** [comment]
Same issue in 2.3.2

**Comment by jsaman19** [comment]
please explain more and more accurate about your issue i checked version 2.3.2 and i didn't see these issues again

**Comment by muhammedgul** [comment]
Here is how it looks in design tab when days and hours are set as hidden:

<img width="109" alt="Ekran Resmi 2020-04-10 03 37 47" src="https://user-images.githubusercontent.com/54336568/78952022-d1d4cf00-7adc-11ea-98e8-4de52e6d35d4.png">

The first two "00"s are not supposed to be there.

**Comment by jsaman19** [comment]
Please update to version 2.3.3
