### ISSUE TITLE
Display issues

### ISSUE THREAD

**Issue by Jacouille** [jsaman19/easyCountDownTimer#6]
Hi again,

i'm having issues with the display of the text.
- The text doesn't update when i call setTime();
- When i start the timer, the first second display a random number before the actual time i set.
- For the last second of the timer, something weird is happening.

Here is a gif to help you better understand
![displaybugs](https://user-images.githubusercontent.com/49291068/77859778-4bb1b200-71d9-11ea-99f8-cd3afc298f18.gif)

Thank you again :)

**Comment by jsaman19** [comment]
Please update to version 2.3.1
