### ISSUE TITLE
Memory leak and counter off by a second

### ISSUE THREAD

**Issue by Jacouille** [jsaman19/easyCountDownTimer#7]
Hi sorry for bodering you again,

The issue with days showing is back. The counter is also off by a second, ex(it displays 59 seconds but the minutes aren't going down, when it hits 0, the last number is 59). 
![displaybugs](https://user-images.githubusercontent.com/49291068/77966168-7b7fb900-72b0-11ea-81ed-e5ec44ca4ba7.gif)
![displaybug2](https://user-images.githubusercontent.com/49291068/77966175-7cb0e600-72b0-11ea-97de-95d5a6410b9c.gif)

While looking at the code, i came accross a memory leak when you have startAutomatically set to true.
![image](https://user-images.githubusercontent.com/49291068/77966198-89cdd500-72b0-11ea-81d7-bd504fcd630a.png)

Thank you for updating the library, it's really appreciated :D

**Comment by jsaman19** [comment]
Please update to version 2.3.2
