### ISSUE TITLE
Please add pause() and resume() methods

### ISSUE THREAD

**Issue by JoykishanSharma** [jsaman19/easyCountDownTimer#9]
Hi @jsaman19 , It would be very helpful if we had pause() and resume() methods for this easyCountDownTimer library. 😊 We could do that by having a custom CountDownTimer abstract class with pause() and resume() mthods. I have tried to add those in this [Pull Request]( #8  ), 😅 please have a look. 
Awesome Library by the way. :+1:

**Comment by jsaman19** [comment]
Hi man, Yes it was a good idea
Thank you👍
